# Generates gfx.h: 2-bit sprites from ASCII art, a 3x5 font, icons and the synth note table.
# Sprite chars: . transparent, o color 1, s color 2, d color 3.
SPR = {
 "HSTAND": ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            ".oooooo.","soddddos",".dddddd.",".dddddd.",".dd..dd.","ddd..ddd"],
 "HRUN1":  ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            ".oooooo.","soddddos",".dddddd.",".ddddd..","dd..ddd.","d....dd."],
 "HRUN2":  ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            ".oooooo.",".oddddo.",".dddddd.","..dddd..","..ddd...","..ddd..."],
 "HJUMP":  ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            "soooooos",".oddddo.",".dddddd.",".dddddd.","dd....dd","d......d"],
 "HTHROW": ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            ".oooooss","sodddd..",".dddddd.","..dddd..",".dd..dd.","dd....dd"],
 "HHANG":  ["......ss","......ss","..ooooos",".oooooos",".ooooods","..sssds.",
            "..sssss.",".ooddd..",".ddddd..","..dddd..","..dd.dd.","..dd.dd."],
 "HCROUCH":["........","........","........","........","........","..oooo..",
            ".oooooo.",".ooooooo","..sssds.","soddddos",".dddddd.","ddd..ddd"],
 "HROLL":  ["........","..oooo..",".oooooo.",".sssdsd.",".sdddds.",".dddddd.","..dddd..","........"],
 "HSPIN":  ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            "soooooos","soddddos",".dddddd.","..dddd..",".dd..dd.","dd....dd"],
 "GRUM1":  ["..d..d..",".oooooo.","oooooooo","ossoosso","osdoosdo","oooooooo",".oddddo.","dd....dd"],
 "GRUM2":  ["..d..d..",".oooooo.","oooooooo","ossoosso","osdoosdo","oooooooo",".oddddo.",".dd..dd."],
 "BUZZ1":  ["ss....ss",".ss..ss.","..oooo..",".oooodo.",".dddddd.",".oooooo.","..dddd..","...dd..."],
 "BUZZ2":  ["........","........","ssooooss",".oooodo.",".dddddd.",".oooooo.","..dddd..","...dd..."],
 "CAP":    ["..oooo..",".oooooo.",".dddddd.","oooooooo"],
}
FONT = {  # 3x5 glyphs
 "0":["###","#.#","#.#","#.#","###"], "1":[".#.","##.",".#.",".#.","###"],
 "2":["###","..#","###","#..","###"], "3":["###","..#","###","..#","###"],
 "4":["#.#","#.#","###","..#","..#"], "5":["###","#..","###","..#","###"],
 "6":["###","#..","###","#.#","###"], "7":["###","..#","..#",".#.",".#."],
 "8":["###","#.#","###","#.#","###"], "9":["###","#.#","###","..#","###"],
 ":":["...",".#.","...",".#.","..."], ".":["...","...","...","...",".#."],
}
ICON = {  # 5x5
 "I_FLAG":  ["##...","####.","###..","#....","#...."],
 "I_SKULL": [".###.","#.#.#","#####",".###.",".#.#."],
 "I_COIN":  [".###.","##.##","##.##","##.##",".###."],
}
out = ["// Generated by gen.py. Do not edit.", "typedef unsigned short u16;"]
for name, rows in SPR.items():
    vals = []
    for r in rows:
        assert len(r) == 8, (name, r)
        v = 0
        for i, ch in enumerate(r):
            v |= ".osd".index(ch) << (14 - 2 * i)
        vals.append("0x%04x" % v)
    out.append("static const u16 %s[%d]={%s};" % (name, len(rows), ",".join(vals)))
def bits(rows):
    v = 0
    for r in rows:
        for ch in r:
            v = v << 1 | (ch == "#")
    return v
out.append("static const unsigned short FONT[12]={%s};" % ",".join(
    "0x%04x" % bits(FONT[c]) for c in "0123456789:."))

# Menu type is drawn from original stroke outlines at 3x the old font resolution.
# A pixel stores 2-bit coverage, giving diagonal edges finer steps and soft corners.
MENU_PATHS = {'A': [[(2, 19), (7, 1), (12, 19)], [(4, 12), (10, 12)]],
 'B': [[(2, 19), (2, 1), (9, 1), (12, 3), (12, 7), (9, 10), (2, 10)],
       [(9, 10), (12, 12), (12, 16), (9, 19), (2, 19)]],
 'C': [[(12, 3), (10, 1), (5, 1), (2, 4), (2, 16), (5, 19), (10, 19), (12, 17)]],
 'D': [[(2, 19), (2, 1), (8, 1), (12, 5), (12, 15), (8, 19), (2, 19)]],
 'E': [[(12, 1), (2, 1), (2, 19), (12, 19)], [(2, 10), (10, 10)]],
 'F': [[(12, 1), (2, 1), (2, 19)], [(2, 10), (10, 10)]],
 'G': [[(12, 3), (10, 1), (5, 1), (2, 4), (2, 16), (5, 19), (10, 19), (12, 17), (12, 11), (8, 11)]],
 'H': [[(2, 1), (2, 19)], [(12, 1), (12, 19)], [(2, 10), (12, 10)]],
 'I': [[(3, 1), (11, 1)], [(7, 1), (7, 19)], [(3, 19), (11, 19)]],
 'J': [[(5, 1), (12, 1), (12, 15), (9, 19), (5, 19), (2, 16)]],
 'K': [[(2, 1), (2, 19)], [(12, 1), (2, 11)], [(6, 7), (12, 19)]],
 'L': [[(2, 1), (2, 19), (12, 19)]],
 'M': [[(2, 19), (2, 1), (7, 10), (12, 1), (12, 19)]],
 'N': [[(2, 19), (2, 1), (12, 19), (12, 1)]],
 'O': [[(5, 1), (9, 1), (12, 4), (12, 16), (9, 19), (5, 19), (2, 16), (2, 4), (5, 1)]],
 'P': [[(2, 19), (2, 1), (9, 1), (12, 4), (12, 8), (9, 11), (2, 11)]],
 'Q': [[(5, 1), (9, 1), (12, 4), (12, 15), (9, 18), (5, 18), (2, 15), (2, 4), (5, 1)],
       [(8, 14), (13, 20)]],
 'R': [[(2, 19), (2, 1), (9, 1), (12, 4), (12, 8), (9, 11), (2, 11)], [(8, 11), (12, 19)]],
 'S': [[(12, 3),
        (10, 1),
        (5, 1),
        (2, 4),
        (2, 7),
        (5, 10),
        (9, 10),
        (12, 13),
        (12, 16),
        (9, 19),
        (4, 19),
        (2, 17)]],
 'T': [[(1, 1), (13, 1)], [(7, 1), (7, 19)]],
 'U': [[(2, 1), (2, 15), (5, 19), (9, 19), (12, 15), (12, 1)]],
 'V': [[(2, 1), (7, 19), (12, 1)]],
 'W': [[(1, 1), (3, 19), (7, 11), (11, 19), (13, 1)]],
 'X': [[(2, 1), (12, 19)], [(12, 1), (2, 19)]],
 'Y': [[(2, 1), (7, 10), (12, 1)], [(7, 10), (7, 19)]],
 'Z': [[(2, 1), (12, 1), (2, 19), (12, 19)]],
 '0': [[(5, 1), (9, 1), (12, 4), (12, 16), (9, 19), (5, 19), (2, 16), (2, 4), (5, 1)],
       [(4, 16), (10, 4)]],
 '1': [[(3, 5), (7, 1), (7, 19)], [(3, 19), (11, 19)]],
 '2': [[(2, 4), (5, 1), (9, 1), (12, 4), (12, 7), (2, 19), (12, 19)]],
 '3': [[(2, 2), (5, 1), (9, 1), (12, 4), (12, 7), (9, 10), (6, 10)],
       [(9, 10), (12, 13), (12, 16), (9, 19), (5, 19), (2, 17)]],
 '4': [[(10, 19), (10, 1), (1, 13), (13, 13)]],
 '5': [[(12, 1), (2, 1), (2, 10), (9, 10), (12, 13), (12, 16), (9, 19), (4, 19), (2, 17)]],
 '6': [[(11, 2),
        (8, 1),
        (5, 2),
        (2, 6),
        (2, 16),
        (5, 19),
        (9, 19),
        (12, 16),
        (12, 12),
        (9, 9),
        (5, 9),
        (2, 12)]],
 '7': [[(2, 1), (12, 1), (5, 19)]],
 '8': [[(5, 1), (9, 1), (12, 4), (12, 7), (9, 10), (5, 10), (2, 7), (2, 4), (5, 1)],
       [(5, 10), (2, 13), (2, 16), (5, 19), (9, 19), (12, 16), (12, 13), (9, 10)]],
 '9': [[(12, 9),
        (9, 12),
        (5, 12),
        (2, 9),
        (2, 4),
        (5, 1),
        (9, 1),
        (12, 4),
        (12, 14),
        (9, 18),
        (6, 19),
        (3, 18)]],
 '-': [[(2, 10), (12, 10)]],
 '/': [[(12, 1), (2, 19)]],
 ':': [[(7, 5), (7, 6)], [(7, 15), (7, 16)]],
 '.': [[(7, 18), (7, 19)]],
 '?': [[(2, 4), (5, 1), (9, 1), (12, 4), (12, 7), (7, 12), (7, 13)], [(7, 18), (7, 19)]]}
def stroke_distance(x, y, a, b):
    vx, vy = b[0]-a[0], b[1]-a[1]
    t = max(0, min(1, ((x-a[0])*vx+(y-a[1])*vy)/(vx*vx+vy*vy)))
    return ((x-a[0]-vx*t)**2+(y-a[1]-vy*t)**2)**0.5
menu_rows = []
for char in "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-/:.?":
    segments = [(a,b) for path in MENU_PATHS[char] for a,b in zip(path,path[1:])]
    rows = []
    for y in range(21):
        packed = 0
        for x in range(15):
            distance = min(stroke_distance(x,y,a,b) for a,b in segments)
            coverage = round(max(0,min(1,2-distance))*3)
            packed = packed*4+coverage
        rows.append(str(packed)+'u')
    menu_rows.append('{'+','.join(rows)+'}')
out.append("static const unsigned MENUFONT[41][21]={%s};" % ','.join(menu_rows))

for name, rows in ICON.items():
    out.append("#define %s 0x%07x" % (name, bits(rows)))
# Phase increments for MIDI 96..107 at 44100 Hz (2^32 * f / 44100); lower octaves shift right.
inc = [round(440 * 2 ** ((n - 69) / 12) * 2**32 / 44100) for n in range(96, 108)]
out.append("static const unsigned NOTE[12]={%s};" % ",".join("%du" % x for x in inc))
# Sine table for sprite rotation: 256 steps per turn, scaled by 256.
import math
out.append("static const short SIN[256]={%s};" % ",".join(str(round(256 * math.sin(i * math.pi / 128))) for i in range(256)))
open("gfx.h", "w").write("\n".join(out) + "\n")
print("ok", len(SPR), "sprites")
