# Generates gfx.h: 2-bit sprites from ASCII art, a 3x5 font, icons and the synth note table.
# Sprite chars: . transparent, o color 1, s color 2, d color 3.
SPR = {
 "HSTAND": ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            ".oooooo.","soddddos",".dddddd.",".dddddd.",".dd..dd.","ddd..ddd"],
 "HRUN1":  ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            ".oooooo.","soddddos",".dddddd.",".ddddd..","dd..ddd.","d....dd."],
 "HRUN2":  ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            ".oooooo.",".oddddo.",".dddddd.","..dddd..","..ddd...","..ddd..."],
 "HJUMP":  ["..oooo..",".oooooo.",".ooooooo","..sssds.","..sssss.","...sss..",
            "soooooos",".oddddo.",".dddddd.",".dddddd.","dd....dd","d......d"],
 "HCROUCH":["........","........","........","..oooo..",".oooooo.",".ooooooo",
            "..sssds.","soooooos",".dddddd.",".dddddd.",".dddddd.","ddd..ddd"],
 "GRUM1":  ["..d..d..",".oooooo.","oooooooo","ossoosso","osdoosdo","oooooooo",".oddddo.","dd....dd"],
 "GRUM2":  ["..d..d..",".oooooo.","oooooooo","ossoosso","osdoosdo","oooooooo",".oddddo.",".dd..dd."],
 "BUZZ1":  ["ss....ss",".ss..ss.","..oooo..",".oooodo.",".dddddd.",".oooooo.","..dddd..","...dd..."],
 "BUZZ2":  ["........","........","ssooooss",".oooodo.",".dddddd.",".oooooo.","..dddd..","...dd..."],
 "CAP":    ["..oooo..",".oooooo.",".dddddd.","oooooooo"],
}
FONT = {  # 3x5 glyphs
 "0":["###","#.#","#.#","#.#","###"], "1":[".#.","##.",".#.",".#.","###"],
 "2":["###","..#","###","#..","###"], "3":["###","..#","###","..#","###"],
 "4":["#.#","#.#","###","..#","..#"], "5":["###","#..","###","..#","###"],
 "6":["###","#..","###","#.#","###"], "7":["###","..#","..#",".#.",".#."],
 "8":["###","#.#","###","#.#","###"], "9":["###","#.#","###","..#","###"],
 ":":["...",".#.","...",".#.","..."], ".":["...","...","...","...",".#."],
}
ICON = {  # 5x5
 "I_FLAG":  ["##...","####.","###..","#....","#...."],
 "I_SKULL": [".###.","#.#.#","#####",".###.",".#.#."],
 "I_COIN":  [".###.","##.##","##.##","##.##",".###."],
}
out = ["// Generated by gen.py. Do not edit.", "typedef unsigned short u16;"]
for name, rows in SPR.items():
    vals = []
    for r in rows:
        assert len(r) == 8, (name, r)
        v = 0
        for i, ch in enumerate(r):
            v |= ".osd".index(ch) << (14 - 2 * i)
        vals.append("0x%04x" % v)
    out.append("static const u16 %s[%d]={%s};" % (name, len(rows), ",".join(vals)))
def bits(rows):
    v = 0
    for r in rows:
        for ch in r:
            v = v << 1 | (ch == "#")
    return v
out.append("static const unsigned short FONT[12]={%s};" % ",".join(
    "0x%04x" % bits(FONT[c]) for c in "0123456789:."))
for name, rows in ICON.items():
    out.append("#define %s 0x%07x" % (name, bits(rows)))
# Phase increments for MIDI 96..107 at 44100 Hz (2^32 * f / 44100); lower octaves shift right.
inc = [round(440 * 2 ** ((n - 69) / 12) * 2**32 / 44100) for n in range(96, 108)]
out.append("static const unsigned NOTE[12]={%s};" % ",".join("%du" % x for x in inc))
# Sine table for sprite rotation: 256 steps per turn, scaled by 256.
import math
out.append("static const short SIN[256]={%s};" % ",".join(str(round(256 * math.sin(i * math.pi / 128))) for i in range(256)))
open("gfx.h", "w").write("\n".join(out) + "\n")
print("ok", len(SPR), "sprites")
