# Embeds assets/levels.txt into levels.h as LEVELS_TXT, the built-in copy of the levels. The game
# and the simulator read assets/levels.txt at startup and fall back to this copy without it.
import json
text = open("assets/levels.txt").read()
lines = "\n".join("  " + json.dumps(l + "\n") for l in text.split("\n"))
open("levels.h", "w").write("// Generated by mklevels.py from assets/levels.txt. Do not edit.\nstatic const char LEVELS_TXT[] =\n" + lines + ";\n")
print("levels:", sum(l.startswith("=") for l in text.split("\n")), "built in")
