# Embeds assets/levels.txt into levels.h as LEVELS_TXT, the built-in copy of the levels. The game
# and the simulator read assets/levels.txt at startup and fall back to this copy without it; the
# format (levels, "+" bonus rooms, every map character) is parsed by the game and documented in
# MODDING.md, and ./sim --check (run by build.sh) reports mistakes with file and line.
import json
text = open("assets/levels.txt").read()
try:   # the new worlds follow (worlds.c reads assets/worlds.txt the same way)
    text = text.rstrip("\n") + "\n" + open("assets/worlds.txt").read()
except FileNotFoundError:
    pass
lines = "\n".join("  " + json.dumps(l + "\n") for l in text.split("\n"))
open("levels.h", "w").write("// Generated by mklevels.py from assets/levels.txt. Do not edit.\nstatic const char LEVELS_TXT[] =\n" + lines + ";\n")
print("levels:", sum(l.startswith("=") for l in text.split("\n")), "built in,",
      sum(l.startswith("+") for l in text.split("\n")), "bonus rooms")
