# Writes music.h (tempo, loop length and "bah" beats per theme) from assets/music/*/loop.json,
# in the order of the T_ enum in sound.h.
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THEMES = ["overworld", "underground", "athletic", "finale"]
STEMS = ["lead", "bass", "perc", "bells", "fast", "arp", "bah"]
rows = []
for t in THEMES:
    m = json.load(open(os.path.join(ROOT, "assets", "music", t, "loop.json")))
    assert m["stems"] == STEMS and m["rate"] == 48000, t
    bahs = ",".join(f"{b:g}" for b in m["bah_beats"])
    rows.append(f'  {{ "{t}", {m["bpm"]}, {m["beats"]}, {m["samples"]}, {len(m["bah_beats"])}, {{ {bahs} }} }},')
out = ["// Generated by audio/mkmusic.py from assets/music/*/loop.json. Do not edit.",
       "static const char *const STEM_NAME[] = { %s };" % ", ".join(f'"{s}"' for s in STEMS),
       "static const struct { const char *name; int bpm, beats, frames, nbah; float bah[16]; } THEME[] = {"] + rows + ["};"]
open(os.path.join(ROOT, "music.h"), "w").write("\n".join(out) + "\n")
